name: flutter_athropic_interface
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/nicolarigoni/flutter_athropic_interface.git

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path: ^1.9.0
  http: ^1.6.0
  dartdoc: ^8.3.4
  analyzer: ^7.3.0 
  source_gen: ^2.0.0
  build: ^2.4.2

dev_dependencies:
  lints: ^6.0.0
  build_runner: ^2.4.0
